version: "3.3"

volumes:
  poetry_libs:
  shared_contexts:
  postgresql-data:
    driver: local

networks:
    common-network:

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "common136"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - common-network

  api:
    hostname: api
    image: jlucasamorim/salz-gmd-setups-api:latest
    command: uvicorn salz_expenditure_management.api:app --host 0.0.0.0 --reload
    stdin_open: true
    tty: true
    volumes:
      - ".:/home/python/app"
      - "poetry_libs:/usr/local/lib"
    environment:
      PYTHONPATH: src
      CORS_ALLOW_CREDENTIALS: "true"
      CORS_ALLOW_HEADERS: "[\"*\"]"
      CORS_ALLOW_METHODS: "[\"*\"]"
      CORS_ALLOW_ORIGINS: "[\"*\"]"
      ENV: "dev"
      LOG_LEVEL: "debug"
      DATABASE_LOGGING_ECHO: "0"
      WEB_APP_DEBUG: "true"
      WEB_APP_DESCRIPTION: "Common Workspaces"
      WEB_APP_TITLE: "Common Workspaces"
      WEB_APP_VERSION: "0.1.0"
      WEB_SERVER_HOST: "0.0.0.0"
      WEB_SERVER_PORT: 8000
      WEB_SERVER_RELOAD: "true"
      ALGORITHM: "HS256"
      ASYNC_SQLALCHEMY_URL: "postgresql+asyncpg://postgres:common136@postgresql/postgres"
      ASYNC_SQLALCHEMY_LOGGING_ECHO: 1
      ASYNC_SQLALCHEMY_POOL_SIZE: 5
      ASYNC_SQLALCHEMY_MAX_POOL_SIZE: 50
    networks:
      - "common-network"
    env_file:
      - ./common.env
    depends_on:
      - postgresql
    ports:
      - "8000:8000"

  client:
    image: jlucasamorim/salz-gmd-setups-client:latest
    ports: 
      - "80:80"
    networks:
      - "common-network"
