version: "3.3"

volumes:
  shared_contexts:
  postgresql-data:
    driver: local

networks:
    common-network:

services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=salz-gmd
      - POSTGRES_PASSWORD=salz-gmd
      - POSTGRES_DB=salz-gmd
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - common-network

  api:
    image: jlucasamorim/salz-gmd-setups-api:latest
    command: ["./app", "-prod"]
    restart: always
    environment:
      - DB_USER=salz-gmd
      - DB_PASSWORD=salz-gmd
      - DB_NAME=salz-gmd
      - DB_HOST=postgresql
      - DB_PORT=5432
      - JWT_SECRET=secret
    networks:
      - "common-network"
    depends_on:
      - postgresql
    ports:
      - "8080:8080"

  nextjs-app:
    image: jlucasamorim/salz-gmd-setups-client:latest
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    networks:
      - "common-network"
    depends_on:
      - api
  nginx:
    image: salz/nginx-app # Placeholder for pushing image to Dockerhub
    build:
      context: ./nginx-docker
      dockerfile: Dockerfile
    networks:
      - "common-network"
    depends_on:
      - nextjs-app
    ports:
      - '80:80'
    environment:
      - NEXTJS_CONTAINER_IP=nextjs-app # supplying environment vars for convert-nginx.sh file.
    command: ['sh', '/etc/nginx/convert-nginx.sh']
